// Synonym Dictionary for Search Enhancement
// 동의어 사전을 통한 검색 품질 개선
// 
// Auto-generated from admin/synonyms_config.json
// Generated at: 2025-08-15 23:22:14
// DO NOT EDIT THIS FILE DIRECTLY - Edit admin/synonyms_config.json instead

const synonymDictionary = {
  "비타민": [
    "vitamin",
    "바이타민",
    "vit",
    "비타민",
    "vitamins"
  ],
  "비타민c": [
    "비타민씨",
    "아스코빅산",
    "vitamin-c",
    "vitamin c",
    "아스코르브산",
    "비타민c",
    "vit c",
    "ascorbic acid"
  ],
  "비타민d": [
    "비타민디",
    "비타민d",
    "vitamin d",
    "vit d",
    "d3",
    "vitamin-d3",
    "d-3",
    "칼시페롤",
    "vitamin-d"
  ],
  "비타민e": [
    "비타민이",
    "mixed tocopherols",
    "vitamin-e",
    "vitamin e",
    "비타민e",
    "vit e",
    "토코페롤",
    "tocopherol"
  ],
  "비타민b": [
    "vit b",
    "vitamin-b",
    "b complex",
    "비타민b",
    "b-컴플렉스",
    "비타민비",
    "비컴플렉스",
    "vitamin b",
    "b-complex"
  ],
  "비타민b12": [
    "비타민b12",
    "비12",
    "메틸코발라민",
    "vitamin b12",
    "b12",
    "코발라민",
    "cobalamin",
    "methylcobalamin"
  ],
  "종합비타민": [
    "multivitamin",
    "종합비타민",
    "종비",
    "멀티비타민",
    "multi vitamin",
    "multi-vitamin",
    "daily vitamin"
  ],
  "칼슘": [
    "calcium",
    "칼슘",
    "칼시움",
    "calcium carbonate",
    "calcium citrate",
    "ca"
  ],
  "마그네슘": [
    "magnesium",
    "mg",
    "마그네시움",
    "마그네슘",
    "magnesium glycinate",
    "magnesium citrate"
  ],
  "아연": [
    "zinc citrate",
    "zinc",
    "zinc picolinate",
    "아연",
    "징크",
    "zn"
  ],
  "철분": [
    "페러스",
    "fe",
    "철",
    "철분",
    "아이언",
    "iron",
    "ferrous"
  ],
  "셀레늄": [
    "셀레니움",
    "셀레늄",
    "selenium",
    "se",
    "selenomethionine"
  ],
  "오메가3": [
    "omega-3",
    "fish oil",
    "피시오일",
    "피쉬오일",
    "dha",
    "epa",
    "omega 3",
    "오메가쓰리",
    "omega3",
    "오메가3",
    "어유"
  ],
  "오메가6": [
    "evening primrose",
    "omega 6",
    "omega-6",
    "gla",
    "omega6",
    "오메가6"
  ],
  "오메가9": [
    "omega 9",
    "omega9",
    "oleic acid",
    "오메가9",
    "omega-9"
  ],
  "유산균": [
    "프로바이오틱",
    "프로바이오틱스",
    "lactobacillus",
    "유산균",
    "probiotics",
    "비피더스",
    "bifidobacterium",
    "락토바실러스",
    "probiotic"
  ],
  "프리바이오틱스": [
    "inulin",
    "프리바이오틱",
    "이눌린",
    "prebiotic",
    "프리바이오틱스",
    "prebiotics"
  ],
  "단백질": [
    "casein",
    "웨이",
    "whey protein",
    "protein",
    "protein powder",
    "단백질",
    "프로틴",
    "whey",
    "카제인"
  ],
  "콜라겐": [
    "collagen peptide",
    "marine collagen",
    "콜라겐",
    "콜라젠",
    "collagen powder",
    "collagen"
  ],
  "bcaa": [
    "valine",
    "branched chain amino acids",
    "비씨에이에이",
    "isoleucine",
    "leucine",
    "bcaa",
    "분지쇄아미노산"
  ],
  "글루타민": [
    "l glutamine",
    "글루타민",
    "glutamine",
    "l-glutamine",
    "엘글루타민"
  ],
  "아르기닌": [
    "아르기닌",
    "aakg",
    "l-arginine",
    "엘아르기닌",
    "arginine",
    "l arginine"
  ],
  "코큐텐": [
    "ubiquinol",
    "co q10",
    "코큐10",
    "코큐텐",
    "q10",
    "coq10",
    "coenzyme q10",
    "코엔자임큐10",
    "유비퀴놀"
  ],
  "글루타치온": [
    "glutathione",
    "글루타치온",
    "reduced glutathione",
    "글루타티온",
    "gsh",
    "liposomal glutathione"
  ],
  "알파리포산": [
    "리포산",
    "alpha lipoic acid",
    "ala",
    "r-lipoic acid",
    "알파리포산",
    "lipoic acid"
  ],
  "레스베라트롤": [
    "resveratrol",
    "trans-resveratrol",
    "레스베라트롤"
  ],
  "글루코사민": [
    "glucosamine hcl",
    "글루코사민",
    "glucosamine",
    "glucosamine sulfate"
  ],
  "msm": [
    "msm",
    "메틸설포닐메탄",
    "methylsulfonyl methane",
    "엠에스엠",
    "methylsulfonylmethane"
  ],
  "콘드로이틴": [
    "콘드로이틴",
    "chondroitin",
    "chondroitin sulfate"
  ],
  "보스웰리아": [
    "frankincense",
    "프랑킨센스",
    "boswellia",
    "보스웰리아",
    "boswellia serrata"
  ],
  "nmn": [
    "nmn",
    "β-nmn",
    "엔엠엔",
    "니코틴아미드 모노뉴클레오티드",
    "nicotinamide mononucleotide"
  ],
  "nad": [
    "엔에이디",
    "nadh",
    "nad+",
    "nad",
    "nicotinamide adenine dinucleotide"
  ],
  "베르베린": [
    "berberine hcl",
    "berberine",
    "버버린",
    "베르베린"
  ],
  "커큐민": [
    "터메릭",
    "커큐민",
    "curcumin",
    "강황",
    "curcumin extract",
    "turmeric",
    "theracurmin"
  ],
  "아슈와간다": [
    "아쉬와간다",
    "sensoril",
    "withania somnifera",
    "아슈와간다",
    "ksm-66",
    "ashwagandha"
  ],
  "다이어트": [
    "weight loss",
    "diet",
    "fat burn",
    "체중감소",
    "weight management",
    "체중감량",
    "지방연소",
    "fat burner",
    "다이어트"
  ],
  "수면": [
    "5-htp",
    "수면",
    "숙면",
    "valerian",
    "멜라토닌",
    "melatonin",
    "sleep",
    "sleep aid"
  ],
  "스트레스": [
    "스트레스",
    "불안",
    "l-theanine",
    "긴장",
    "anxiety",
    "relax",
    "calm",
    "stress",
    "테아닌"
  ],
  "면역": [
    "면역력",
    "면역",
    "immune",
    "elderberry",
    "immunity",
    "엘더베리",
    "immune support"
  ],
  "소화": [
    "enzyme",
    "digestion",
    "소화",
    "엔자임",
    "소화효소",
    "betaine hcl",
    "digestive enzymes",
    "digestive"
  ],
  "쏜": [
    "손",
    "쏜리서치",
    "쏜",
    "thorne",
    "thorne research",
    "손리서치"
  ],
  "나우": [
    "나우",
    "now foods",
    "나우푸드",
    "now",
    "now food"
  ],
  "닥터스베스트": [
    "닥터스베스트",
    "dr best",
    "닥터베스트",
    "doctor's best",
    "doctors best"
  ],
  "라이프익스텐션": [
    "라이프 익스텐션",
    "life extension",
    "lef",
    "라이프익스텐션",
    "le"
  ],
  "재로우": [
    "jarrow",
    "jarrow formulas",
    "자로우",
    "jarrow formula",
    "재로우"
  ],
  "솔가": [
    "solgar",
    "솔거",
    "솔가"
  ],
  "네이처스웨이": [
    "네이쳐스웨이",
    "nature's way",
    "natures way",
    "네이처스웨이",
    "nature way"
  ],
  "가든오브라이프": [
    "garden of life",
    "gol",
    "가든오브라이프",
    "가든 오브 라이프"
  ],
  "캡슐": [
    "capsules",
    "캡슐",
    "veggie caps",
    "cap",
    "capsule",
    "vcaps",
    "caps"
  ],
  "정": [
    "tablets",
    "타블렛",
    "tablet",
    "태블릿",
    "tabs",
    "정",
    "tab"
  ],
  "액상": [
    "액상",
    "syrup",
    "시럽",
    "drops",
    "tincture",
    "liquid",
    "리퀴드"
  ],
  "파우더": [
    "파우더",
    "powdered",
    "가루",
    "powder",
    "분말",
    "pwd"
  ],
  "구미": [
    "젤리",
    "gummy bears",
    "구미",
    "gummy",
    "gummies"
  ],
  "소프트젤": [
    "소프트젤",
    "softgel",
    "소프트겔",
    "soft gel",
    "liquid caps",
    "softgels"
  ]
};

// 검색어를 동의어로 확장하는 함수
function expandSearchTerms(query) {
    const lowerQuery = query.toLowerCase().trim();
    const expandedTerms = new Set([lowerQuery]); // 원래 검색어 포함
    
    // 각 동의어 그룹을 확인
    for (const [key, synonyms] of Object.entries(synonymDictionary)) {
        // 검색어가 키와 일치하는지 확인
        if (key === lowerQuery) {
            synonyms.forEach(synonym => expandedTerms.add(synonym.toLowerCase()));
        }
        
        // 검색어가 동의어 목록에 있는지 확인
        for (const synonym of synonyms) {
            if (synonym.toLowerCase() === lowerQuery) {
                // 해당 그룹의 모든 동의어 추가
                expandedTerms.add(key);
                synonyms.forEach(s => expandedTerms.add(s.toLowerCase()));
                break;
            }
        }
    }
    
    // 복합 검색어 처리 (예: "thorne 비타민d")
    const words = lowerQuery.split(/\s+/);
    if (words.length > 1) {
        const expandedWords = words.map(word => {
            const wordExpanded = new Set([word]);
            
            for (const [key, synonyms] of Object.entries(synonymDictionary)) {
                if (key === word) {
                    synonyms.forEach(synonym => wordExpanded.add(synonym.toLowerCase()));
                }
                
                for (const synonym of synonyms) {
                    if (synonym.toLowerCase() === word) {
                        wordExpanded.add(key);
                        synonyms.forEach(s => wordExpanded.add(s.toLowerCase()));
                        break;
                    }
                }
            }
            
            return Array.from(wordExpanded);
        });
        
        // 확장된 단어들의 조합 생성 (최대 5개 조합으로 제한)
        const combinations = [];
        for (const word0 of expandedWords[0].slice(0, 3)) {
            if (expandedWords[1]) {
                for (const word1 of expandedWords[1].slice(0, 3)) {
                    combinations.push(`${word0} ${word1}`);
                }
            }
        }
        
        combinations.slice(0, 5).forEach(combo => expandedTerms.add(combo));
    }
    
    return Array.from(expandedTerms);
}

// 검색 매칭 함수 (부분 일치 지원)
function searchWithSynonyms(searchableText, query) {
    const expandedTerms = expandSearchTerms(query);
    const lowerText = searchableText.toLowerCase();
    
    // 확장된 검색어 중 하나라도 텍스트에 포함되면 true
    return expandedTerms.some(term => lowerText.includes(term));
}

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { expandSearchTerms, searchWithSynonyms, synonymDictionary };
}
