// Synonym Dictionary for Search Enhancement
// 동의어 사전을 통한 검색 품질 개선
// 
// Auto-generated from admin/synonyms_config.json
// Generated at: 2026-06-06 20:27:03
// DO NOT EDIT THIS FILE DIRECTLY - Edit admin/synonyms_config.json instead

const synonymDictionary = {
  "비타민": [
    "vit",
    "vitamin",
    "바이타민",
    "비타민",
    "vitamins"
  ],
  "비타민c": [
    "아스코르브산",
    "vitamin-c",
    "비타민씨",
    "vit c",
    "vitamin c",
    "비타민c",
    "ascorbic acid",
    "아스코빅산"
  ],
  "비타민d": [
    "vitamin d",
    "vitamin-d3",
    "비타민디",
    "d-3",
    "비타민d",
    "d3",
    "vitamin-d",
    "칼시페롤",
    "vit d"
  ],
  "비타민e": [
    "비타민이",
    "비타민e",
    "vitamin e",
    "토코페롤",
    "vitamin-e",
    "vit e",
    "tocopherol",
    "mixed tocopherols"
  ],
  "비타민b": [
    "비컴플렉스",
    "b-컴플렉스",
    "vit b",
    "b-complex",
    "비타민b",
    "vitamin b",
    "비타민비",
    "vitamin-b",
    "b complex"
  ],
  "비타민b12": [
    "코발라민",
    "methylcobalamin",
    "메틸코발라민",
    "비타민b12",
    "vitamin b12",
    "cobalamin",
    "b12",
    "비12"
  ],
  "종합비타민": [
    "multi-vitamin",
    "multi vitamin",
    "multivitamin",
    "종비",
    "daily vitamin",
    "멀티비타민",
    "종합비타민"
  ],
  "칼슘": [
    "calcium citrate",
    "ca",
    "칼시움",
    "calcium",
    "calcium carbonate",
    "칼슘"
  ],
  "마그네슘": [
    "마그네슘",
    "magnesium glycinate",
    "magnesium",
    "mg",
    "magnesium citrate",
    "마그네시움"
  ],
  "아연": [
    "징크",
    "아연",
    "zinc",
    "zinc citrate",
    "zn",
    "zinc picolinate"
  ],
  "철분": [
    "iron",
    "철",
    "페러스",
    "아이언",
    "ferrous",
    "fe",
    "철분"
  ],
  "셀레늄": [
    "셀레니움",
    "selenomethionine",
    "se",
    "셀레늄",
    "selenium"
  ],
  "오메가3": [
    "dha",
    "omega 3",
    "omega3",
    "오메가쓰리",
    "fish oil",
    "epa",
    "피쉬오일",
    "omega-3",
    "피시오일",
    "어유",
    "오메가3"
  ],
  "오메가6": [
    "omega 6",
    "오메가6",
    "evening primrose",
    "omega6",
    "gla",
    "omega-6"
  ],
  "오메가9": [
    "오메가9",
    "oleic acid",
    "omega9",
    "omega-9",
    "omega 9"
  ],
  "유산균": [
    "probiotics",
    "probiotic",
    "프로바이오틱",
    "bifidobacterium",
    "유산균",
    "락토바실러스",
    "lactobacillus",
    "프로바이오틱스",
    "비피더스"
  ],
  "프리바이오틱스": [
    "프리바이오틱스",
    "식이섬유",
    "prebiotics",
    "inulin",
    "prebiotic",
    "프리바이오틱",
    "이눌린"
  ],
  "단백질": [
    "whey",
    "protein",
    "단백질",
    "카제인",
    "whey protein",
    "casein",
    "프로틴",
    "웨이",
    "protein powder"
  ],
  "콜라겐": [
    "marine collagen",
    "콜라겐",
    "콜라젠",
    "collagen powder",
    "collagen",
    "collagen peptide"
  ],
  "bcaa": [
    "valine",
    "분지쇄아미노산",
    "leucine",
    "bcaa",
    "branched chain amino acids",
    "isoleucine",
    "비씨에이에이"
  ],
  "글루타민": [
    "글루타민",
    "l glutamine",
    "glutamine",
    "엘글루타민",
    "l-glutamine"
  ],
  "아르기닌": [
    "l-arginine",
    "aakg",
    "l arginine",
    "아르기닌",
    "arginine",
    "엘아르기닌"
  ],
  "코큐텐": [
    "coenzyme q10",
    "q10",
    "coq10",
    "ubiquinol",
    "코엔자임큐10",
    "코큐10",
    "유비퀴놀",
    "co q10",
    "코큐텐"
  ],
  "글루타치온": [
    "glutathione",
    "liposomal glutathione",
    "reduced glutathione",
    "글루타치온",
    "글루타티온",
    "gsh"
  ],
  "알파리포산": [
    "리포산",
    "알파리포산",
    "ala",
    "r-lipoic acid",
    "alpha lipoic acid",
    "lipoic acid"
  ],
  "레스베라트롤": [
    "resveratrol",
    "trans-resveratrol",
    "레스베라트롤"
  ],
  "글루코사민": [
    "glucosamine",
    "glucosamine hcl",
    "glucosamine sulfate",
    "글루코사민"
  ],
  "msm": [
    "메틸설포닐메탄",
    "엠에스엠",
    "methylsulfonyl methane",
    "methylsulfonylmethane",
    "msm"
  ],
  "콘드로이틴": [
    "chondroitin sulfate",
    "chondroitin",
    "콘드로이틴"
  ],
  "보스웰리아": [
    "프랑킨센스",
    "boswellia serrata",
    "보스웰리아",
    "boswellia",
    "frankincense"
  ],
  "nmn": [
    "β-nmn",
    "니코틴아미드 모노뉴클레오티드",
    "엔엠엔",
    "nicotinamide mononucleotide",
    "nmn"
  ],
  "nad": [
    "엔에이디",
    "nicotinamide adenine dinucleotide",
    "nad",
    "nadh",
    "nad+"
  ],
  "베르베린": [
    "berberine",
    "버버린",
    "베르베린",
    "berberine hcl"
  ],
  "커큐민": [
    "커큐민",
    "터메릭",
    "turmeric",
    "theracurmin",
    "curcumin extract",
    "강황",
    "curcumin"
  ],
  "아슈와간다": [
    "ksm-66",
    "아쉬와간다",
    "sensoril",
    "withania somnifera",
    "ashwagandha",
    "아슈와간다"
  ],
  "다이어트": [
    "weight loss",
    "diet",
    "fat burner",
    "체중감소",
    "다이어트",
    "fat burn",
    "weight management",
    "체중감량",
    "지방연소"
  ],
  "수면": [
    "melatonin",
    "sleep",
    "sleep aid",
    "멜라토닌",
    "수면",
    "5-htp",
    "valerian",
    "숙면"
  ],
  "스트레스": [
    "테아닌",
    "anxiety",
    "l-theanine",
    "relax",
    "stress",
    "불안",
    "calm",
    "스트레스",
    "긴장"
  ],
  "면역": [
    "immune",
    "immunity",
    "면역력",
    "elderberry",
    "엘더베리",
    "immune support",
    "면역"
  ],
  "소화": [
    "enzyme",
    "digestive",
    "digestion",
    "소화",
    "소화효소",
    "betaine hcl",
    "digestive enzymes",
    "엔자임"
  ],
  "쏜": [
    "손",
    "thorne research",
    "손리서치",
    "쏜리서치",
    "쏜",
    "thorne"
  ],
  "나우": [
    "now foods",
    "now",
    "나우푸드",
    "나우",
    "now food"
  ],
  "닥터스베스트": [
    "닥터스베스트",
    "doctors best",
    "닥터베스트",
    "doctor's best",
    "dr best"
  ],
  "라이프익스텐션": [
    "le",
    "lef",
    "라이프익스텐션",
    "라이프 익스텐션",
    "life extension"
  ],
  "재로우": [
    "jarrow formula",
    "jarrow formulas",
    "jarrow",
    "재로우",
    "자로우"
  ],
  "솔가": [
    "솔가",
    "solgar",
    "솔거"
  ],
  "네이처스웨이": [
    "natures way",
    "nature way",
    "네이쳐스웨이",
    "네이처스웨이",
    "nature's way"
  ],
  "가든오브라이프": [
    "gol",
    "가든 오브 라이프",
    "garden of life",
    "가든오브라이프"
  ],
  "쿄릭": [
    "쿄릭",
    "교릭",
    "kyolic"
  ],
  "스완슨": [
    "swanson",
    "스완슨",
    "스완손"
  ],
  "캡슐": [
    "veggie caps",
    "캡슐",
    "caps",
    "capsule",
    "cap",
    "capsules",
    "vcaps"
  ],
  "정": [
    "타블렛",
    "tablets",
    "tablet",
    "tab",
    "tabs",
    "태블릿",
    "정"
  ],
  "액상": [
    "liquid",
    "리퀴드",
    "시럽",
    "tincture",
    "drops",
    "syrup",
    "액상"
  ],
  "파우더": [
    "pwd",
    "파우더",
    "가루",
    "powder",
    "분말",
    "powdered"
  ],
  "구미": [
    "gummy",
    "gummies",
    "구미",
    "젤리",
    "gummy bears"
  ],
  "소프트젤": [
    "소프트겔",
    "liquid caps",
    "soft gel",
    "softgels",
    "softgel",
    "소프트젤"
  ]
};

// 검색어를 동의어로 확장하는 함수
function expandSearchTerms(query) {
    const lowerQuery = query.toLowerCase().trim();
    const expandedTerms = new Set([lowerQuery]); // 원래 검색어 포함
    
    // 각 동의어 그룹을 확인
    for (const [key, synonyms] of Object.entries(synonymDictionary)) {
        // 검색어가 키와 일치하는지 확인
        if (key === lowerQuery) {
            synonyms.forEach(synonym => expandedTerms.add(synonym.toLowerCase()));
        }
        
        // 검색어가 동의어 목록에 있는지 확인
        for (const synonym of synonyms) {
            if (synonym.toLowerCase() === lowerQuery) {
                // 해당 그룹의 모든 동의어 추가
                expandedTerms.add(key);
                synonyms.forEach(s => expandedTerms.add(s.toLowerCase()));
                break;
            }
        }
    }
    
    // 복합 검색어 처리 (예: "thorne 비타민d")
    const words = lowerQuery.split(/\s+/);
    if (words.length > 1) {
        const expandedWords = words.map(word => {
            const wordExpanded = new Set([word]);
            
            for (const [key, synonyms] of Object.entries(synonymDictionary)) {
                if (key === word) {
                    synonyms.forEach(synonym => wordExpanded.add(synonym.toLowerCase()));
                }
                
                for (const synonym of synonyms) {
                    if (synonym.toLowerCase() === word) {
                        wordExpanded.add(key);
                        synonyms.forEach(s => wordExpanded.add(s.toLowerCase()));
                        break;
                    }
                }
            }
            
            return Array.from(wordExpanded);
        });
        
        // 확장된 단어들의 조합 생성 (최대 5개 조합으로 제한)
        const combinations = [];
        for (const word0 of expandedWords[0].slice(0, 3)) {
            if (expandedWords[1]) {
                for (const word1 of expandedWords[1].slice(0, 3)) {
                    combinations.push(`${word0} ${word1}`);
                }
            }
        }
        
        combinations.slice(0, 5).forEach(combo => expandedTerms.add(combo));
    }
    
    return Array.from(expandedTerms);
}

function normalizeSearchValue(value) {
    return String(value || '').toLowerCase().trim().replace(/\s+/g, ' ');
}

let knownSearchTermsCache = null;

function getKnownSearchTerms() {
    if (knownSearchTermsCache) return knownSearchTermsCache;

    knownSearchTermsCache = new Set();
    for (const [key, synonyms] of Object.entries(synonymDictionary)) {
        knownSearchTermsCache.add(normalizeSearchValue(key));
        synonyms.forEach(synonym => knownSearchTermsCache.add(normalizeSearchValue(synonym)));
    }
    return knownSearchTermsCache;
}

function tokenizeSearchQuery(query) {
    const words = normalizeSearchValue(query).split(/\s+/).filter(Boolean);
    if (words.length <= 1) return words;

    const knownTerms = getKnownSearchTerms();
    const tokens = [];
    let index = 0;

    while (index < words.length) {
        let matchedTerm = null;
        let matchedLength = 0;

        for (let length = words.length - index; length > 0; length--) {
            const candidate = words.slice(index, index + length).join(' ');
            if (knownTerms.has(candidate)) {
                matchedTerm = candidate;
                matchedLength = length;
                break;
            }
        }

        if (matchedTerm) {
            tokens.push(matchedTerm);
            index += matchedLength;
        } else {
            tokens.push(words[index]);
            index += 1;
        }
    }

    return tokens;
}

function isShortAsciiAlias(term) {
    return /^[a-z]{1,2}$/.test(term);
}

function termMatchesText(lowerText, term) {
    const normalizedTerm = normalizeSearchValue(term);
    if (!normalizedTerm) return false;
    if (!isShortAsciiAlias(normalizedTerm)) return lowerText.includes(normalizedTerm);

    const escapedTerm = normalizedTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const boundaryPattern = new RegExp(`(^|[^a-z0-9가-힣])${escapedTerm}($|[^a-z0-9가-힣])`, 'i');
    return boundaryPattern.test(lowerText);
}

function buildFallbackSearch(product) {
    const brand = normalizeSearchValue(product?.brand);
    const name = normalizeSearchValue(product?.name);
    const text = normalizeSearchValue([
        product?.brand,
        product?.name,
        product?.full_text,
        product?.full_text_without_brand,
        product?.form_and_quantity
    ].filter(Boolean).join(' '));
    return {
        brand,
        name,
        text,
        tokens: text ? Array.from(new Set(text.split(/\s+/))) : []
    };
}

function getProductSearch(product) {
    const search = product?.search || {};
    const fallback = buildFallbackSearch(product || {});
    return {
        brand: normalizeSearchValue(search.brand || fallback.brand),
        name: normalizeSearchValue(search.name || fallback.name),
        text: normalizeSearchValue(search.text || fallback.text),
        tokens: Array.isArray(search.tokens) && search.tokens.length > 0
            ? search.tokens.map(token => normalizeSearchValue(token)).filter(Boolean)
            : fallback.tokens
    };
}

function textMatchesQueryTerms(text, queryTerms) {
    const lowerText = normalizeSearchValue(text);
    return queryTerms.every(term => {
        const expandedTerms = expandSearchTerms(term);
        return expandedTerms.some(expandedTerm => termMatchesText(lowerText, expandedTerm));
    });
}

function textMatchesQueryTerm(text, term) {
    const lowerText = normalizeSearchValue(text);
    const expandedTerms = expandSearchTerms(term);
    return expandedTerms.some(expandedTerm => termMatchesText(lowerText, expandedTerm));
}

function tokensMatchQueryTerms(tokens, queryTerms) {
    const tokenText = Array.isArray(tokens) ? tokens.join(' ') : '';
    return textMatchesQueryTerms(tokenText, queryTerms);
}

// 검색 매칭 함수 (부분 일치 지원)
function searchWithSynonyms(searchableText, query) {
    const queryTerms = tokenizeSearchQuery(query);
    if (queryTerms.length === 0) return true;

    const lowerText = normalizeSearchValue(searchableText);

    return queryTerms.every(term => {
        const expandedTerms = expandSearchTerms(term);
        return expandedTerms.some(expandedTerm => termMatchesText(lowerText, expandedTerm));
    });
}

function scoreSearchMatch(product, query) {
    const queryTerms = tokenizeSearchQuery(query);
    if (queryTerms.length === 0) return 0;

    const search = getProductSearch(product || {});
    const matchesAnySearchTarget = [
        search.brand,
        search.name,
        search.text,
        search.tokens.join(' ')
    ].some(value => textMatchesQueryTerms(value, queryTerms));
    if (!matchesAnySearchTarget) return 0;

    let score = 0;
    queryTerms.forEach(term => {
        if (textMatchesQueryTerm(search.brand, term)) score += 100;
        if (textMatchesQueryTerm(search.name, term)) score += 80;
    });
    if (textMatchesQueryTerms(`${search.brand} ${search.name}`, queryTerms)) score += 40;
    if (textMatchesQueryTerms(search.text, queryTerms)) score += 20;
    if (tokensMatchQueryTerms(search.tokens, queryTerms)) score += 10;
    return score;
}

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { expandSearchTerms, searchWithSynonyms, scoreSearchMatch, synonymDictionary };
}
